### ISSUE TITLE
Transitions with delays only check for the condition once

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-libstates#11]
When adding a delay to a condition, it only checks for the condition once

https://github.com/user-attachments/assets/6e6f425a-a644-4327-849b-3c9fa3d768c7

https://github.com/user-attachments/assets/33b3f8d8-ea68-497d-b6cc-133587a4a086

**Comment by Metapyziks** [comment]
That's the intended behaviour, but maybe it's not what most people would expect. I'll think about it some more.

**Comment by Nolankicks** [comment]
There should at least be an option for it. I think it would be fine if a normal transition only checked for it once but it concurrently checks.

**Comment by Metapyziks** [comment]
How about you can specify a min and max delay. If you give a condition, it'll transition as soon as that condition is true while in the delay window. Otherwise, it'll pick a uniformly random delay within the window.

**Comment by Nolankicks** [comment]
That sounds good to me
